# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 120
checkpoint_frequency: 30
batch_size: 32
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/RTM2D_industry_2/
subset_list: [37kpts_v3_20fps]
dt_file: RTM2D_industry_2/37kpts_v3_20fps/rtmpose_v3_20fps_industry_2_37kpts_v2.pkl

# data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/RTM2D_industry/
# subset_list: [37kpts_v3_20fps]
# dt_file: RTM2D_industry/37kpts_v3_20fps/rtmpose_v3_20fps_industry_37kpts_v2.pkl

clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 37
joint_format: RTM-37
no_conf: False
gt_2d: False
root_idx: 0
res_w: 1920
res_h: 1200

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
