# General  
finetune: False
partial_train: null
train_pw3d: False
warmup_h36m: 100

# Training
epochs: 100
checkpoint_frequency: 25
batch_size: 180
batch_size_img: 512
dropout: 0.1
dropout_loc: 1
lr_backbone: 0.0001
lr_head: 0.0001
weight_decay: 0.01
lr_decay: 0.98

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True
hidden_dim: 1024

# Data
data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/mesh
dt_file_VEHS7M: /VEHS_SMPL_6D/VEHS_6D_downsample5_keep1_66_v2_SMPL.pkl
clip_len: 16
data_stride: 8
sample_stride: 1
num_joints: 66
root_idx: 57

# Loss
lambda_3d: 0.5
lambda_scale: 0
lambda_3dv: 10
lambda_lv: 0
lambda_lg: 0
lambda_a: 0
lambda_av: 0
lambda_pose: 1000
lambda_shape: 1
lambda_norm: 20
loss_type: 'L1'

# Augmentation
flip: True