# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 120
checkpoint_frequency: 30
batch_size: 32
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
# /nfs/turbo/coe-shdpm/leyang/VEHS_MB/viewpoint_augmentation/single_cam/pitch_correct/VEHS_6D_downsample5_keep1_37_oneCam.pkl
# this_dt_root = '/'.join(path_components[:-2]) --> two overlapping
data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/viewpoint_augmentation/single_cam
subset_list: [normal]
dt_file: viewpoint_augmentation/single_cam/normal/VEHS_6D_downsample5_keep1_37_oneCam.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 37
joint_format: RTM-37
no_conf: False
gt_2d: True
root_idx: 0
res_w: 1920
res_h: 1200

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.5
lambda_lg: 0.5
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.0
mask_T_ratio: 0.0
noise: False
noise_path: params/synthetic_noise.pth
d2c_params_path: params/d2c_params.pkl