# General  
train_2d: False
no_eval: False
finetune: False
partial_train: null

# Traning 
epochs: 120
checkpoint_frequency: 60
batch_size: 16 
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.99

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
data_root: /nfs/turbo/coe-shdpm/leyang/VEHS_MB/
subset_list: [Rokoko_hand]
dt_file: VEHS_MB/Rokoko_hand/Rokoko_hand_3D_downsample1_keep1.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 21
joint_format: Hand-21
no_conf: False
gt_2d: False
root_idx: 0
res_w: 1000
res_h: 1000

# Loss
lambda_3d_velocity: 20.0
lambda_scale: 0.5
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0

# Augmentation
synthetic: False
flip: False
mask_ratio: 0.05
mask_T_ratio: 0.1
noise: True
noise_path: params/synthetic_noise.pth
d2c_params_path: params/d2c_params.pkl

